name: geno-lecture
channels:
  - conda-forge
  - bioconda
dependencies:
  - openssl
  - numpy
  - pandas
  - mafft
  - r-base
  - r-ggplot2
  - r-openssl
  - r-phangorn
  - r-pheatmap
  - samtools
  - bcftools==1.22