name: geno-lecture
channels:
  - conda-forge
  - bioconda
dependencies:
  - openssl
  - r-openssl
  - numpy
  - pandas
  - r-base=4
  - r-ggplot2=3.3.2
  - mafft
  - r-phangorn
  - r-pheatmap
  - samtools
  - bcftools
  - libssl
